ange_tui / ANGE: ange.h File Reference
ange.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <termios.h>
#include <sys/select.h>
Classes
struct ange_input_t
Represents a keyboard input event.
struct ange_button_t
Represents a button element.
struct ange_radio_option_t
Represents a single radio option.
struct ange_radio_group_t
Represents a group of radio options.
struct ange_navitem_t
Represents an item in a navigation bar.
Enumerations
enum ange_key_t {
ANGE_KEY_UNKNOWN = 0 , ANGE_KEY_ENTER , ANGE_KEY_BACKSPACE , ANGE_KEY_ARROW_UP ,
ANGE_KEY_ARROW_DOWN , ANGE_KEY_ARROW_LEFT , ANGE_KEY_ARROW_RIGHT , ANGE_KEY_ESCAPE ,
ANGE_KEY_CHAR
}
Enum representing supported key input types.
enum ange_align_t { ANGE_ALIGN_LEFT , ANGE_ALIGN_CENTER , ANGE_ALIGN_RIGHT }
Text alignment options for printing.
Functions
static void SaveCurPos ()
(Development use) Saves the current cursor position in the terminal.
static void RestoreCurPos ()
(Development use) Restores the cursor position previously saved.
static int getColSize ()
Returns integer value to terminal coloumn size.
static ange_input_t angeReadKey (void)
Reads a key press from standard input and returns it as an ange_input_t structure.
static void angeInit (void)
Initializes the TUI by setting the terminal to raw mode and clearing the screen.
static void angeKill (void)
Restores the terminal to its original settings and shows the cursor.
void angeClear ()
Clears the screen.
static void angePrintP (const char *text, ange_align_t align)
Prints a paragraph of text aligned within the terminal width.
static void angePrintP_Unaligned (const char *text)
Prints a paragraph of text without any alignment (left aligned by default).
static void angePrintP_yAlign (const char *text, int y_padding_amount)
Prints a paragraph of text with vertical alignment.
static void angePrintHeader (const char *text)
Prints a header line with larger size.
static void angeDrawButton (ange_button_t *buttons, int count, int selected_index)
Draws buttons with one selected but does not handle user input.
static int angeInputButton (ange_button_t *buttons, int count)
Draws a list of buttons and handles user input to select one.
static int angeInputRadio (ange_radio_group_t *group)
Displays a group of radio options and lets the user select one.
static void angeDrawTextbox (char *buffer, int max_len)
Draws a textbox allowing the user to input text.
static void angeDrawBox (int x, int y, int width, int height, const char *title)
Draws a rectangular box (group box) with optional title at specified position.
static int angeDrawNavbar (ange_navitem_t *items, int count, int selected_index)
Draws a navigation bar with items and handles user input to select one.
Variables
static struct termios tui_orig_termios
static int ange_initialized = 0
Enumeration Type Documentation
ange_align_t
enum ange_align_t
Text alignment options for printing.
Enumerator
ANGE_ALIGN_LEFT
Left aligned text
ANGE_ALIGN_CENTER
Center aligned text
ANGE_ALIGN_RIGHT
Right aligned text
Definition at line 196 of file ange.h.
             {
    ANGE_ALIGN_LEFT,
    ANGE_ALIGN_CENTER,
    ANGE_ALIGN_RIGHT
} ange_align_t;
ange_key_t
enum ange_key_t
Enum representing supported key input types.
Enumerator
ANGE_KEY_UNKNOWN
Unknown key
ANGE_KEY_ENTER
Enter key
ANGE_KEY_BACKSPACE
Backspace key
ANGE_KEY_ARROW_UP
Up arrow key
ANGE_KEY_ARROW_DOWN
Down arrow key
ANGE_KEY_ARROW_LEFT
Left arrow key
ANGE_KEY_ARROW_RIGHT
Right arrow key
ANGE_KEY_ESCAPE
Escape key
ANGE_KEY_CHAR
Printable character
Definition at line 49 of file ange.h.
             {
    ANGE_KEY_UNKNOWN = 0,
    ANGE_KEY_ENTER,
    ANGE_KEY_BACKSPACE,
    ANGE_KEY_ARROW_UP,
    ANGE_KEY_ARROW_DOWN,
    ANGE_KEY_ARROW_LEFT,
    ANGE_KEY_ARROW_RIGHT,
    ANGE_KEY_ESCAPE,
    ANGE_KEY_CHAR
} ange_key_t;
Function Documentation
angeClear()
void angeClear ()
Clears the screen.
Definition at line 241 of file ange.h.
                 {
    printf("\033[2J\033[H");
}
angeDrawBox()
static void angeDrawBox (int x, int y, int width, int height, const char * title) static
Draws a rectangular box (group box) with optional title at specified position.
Uses box-drawing characters for the frame.
Parameters
x X coordinate of the top-left corner (1-based column).
y Y coordinate of the top-left corner (1-based row).
width Width of the box.
height Height of the box.
title Optional title to display in the top border.
Definition at line 458 of file ange.h.
{
    printf("\033[%d;%dH┌", y, x);
    for (int i = 0; i < width - 2; i++) printf("─");
    printf("┐");
    for (int i = 1; i < height - 1; i++) {
        printf("\033[%d;%dH│", y + i, x);
        printf("\033[%d;%dH│", y + i, x + width - 1);
    }
    printf("\033[%d;%dH└", y + height - 1, x);
    for (int i = 0; i < width - 2; i++) printf("─");
    printf("┘");
    if (title) {
        printf("\033[%d;%dH[%s]", y, x + 2, title);
    }
    fflush(stdout);
}
angeDrawButton()
static void angeDrawButton (ange_button_t * buttons, int count, int selected_index) static
Draws buttons with one selected but does not handle user input.
Parameters
buttons Array of ange_button_t buttons.
count Number of buttons.
selected_index Index of the currently selected button.
Definition at line 331 of file ange.h.
{
    printf("\033[H");
    for (int i = 0; i < count; i++) {
        if (i == selected_index)
            printf("[ %s ]\n", buttons[i].label);
        else
            printf("[ %s ]\n", buttons[i].label);
    }
    fflush(stdout);
}
Referenced by angeInputButton().
angeDrawNavbar()
static int angeDrawNavbar (ange_navitem_t * items, int count, int selected_index) static
Draws a navigation bar with items and handles user input to select one.
Supports navigation with left/right arrow keys, selection with Enter, and hotkey activation.
Parameters
items Array of ange_navitem_t navigation items.
count Number of navigation items.
selected_index Index of the initially selected item.
Returns
Index of the selected navigation item.
Definition at line 490 of file ange.h.
{
    while (1) {
        printf("\033[H");
        for (int i = 0; i < count; i++) {
            if (i == selected_index)
                printf("[\033[7m%s\033[0m] ", items[i].label);
            else
                printf("[%s] ", items[i].label);
        }
        printf("\n");
        fflush(stdout);
        ange_input_t input = angeReadKey();
        if (input.type == ANGE_KEY_ARROW_LEFT) {
            selected_index = (selected_index - 1 + count) % count;
        } else if (input.type == ANGE_KEY_ARROW_RIGHT) {
            selected_index = (selected_index + 1) % count;
        } else if (input.type == ANGE_KEY_ENTER) {
            return selected_index;
        } else if (input.type == ANGE_KEY_CHAR) {
            for (int i = 0; i < count; i++) {
                if (items[i].hotkey == input.ch || items[i].hotkey == input.ch + 32) {
                    return i;
                }
            }
        }
    }
}
References ANGE_KEY_ARROW_LEFT, ANGE_KEY_ARROW_RIGHT, ANGE_KEY_CHAR, ANGE_KEY_ENTER, angeReadKey(), ange_input_t::ch, ange_navitem_t::hotkey, and ange_input_t::type.
angeDrawTextbox()
static void angeDrawTextbox (char * buffer, int max_len) static
Draws a textbox allowing the user to input text.
Supports typing characters, backspace (ASCII 127), and finishing input with Enter.
Parameters
buffer Character buffer to store input. Must be preallocated.
max_len Maximum length of the input buffer.
Definition at line 425 of file ange.h.
{
    int len = 0;
    buffer[0] = '\0';
    while (1) {
        printf("\033[H> %s ", buffer);
        fflush(stdout);
        ange_input_t input = angeReadKey();
        if (input.type == ANGE_KEY_BACKSPACE && len > 0) {
            len--;
            buffer[len] = '\0';
        } else if (input.type == ANGE_KEY_CHAR && len < max_len - 1) {
            buffer[len++] = input.ch;
            buffer[len] = '\0';
        } else if (input.type == ANGE_KEY_ENTER) {
            break;
        }
    }
}
References ANGE_KEY_BACKSPACE, ANGE_KEY_CHAR, ANGE_KEY_ENTER, angeReadKey(), ange_input_t::ch, and ange_input_t::type.
angeInit()
static void angeInit (void) static
Initializes the TUI by setting the terminal to raw mode and clearing the screen.
Disables canonical mode and echo, hides the cursor, and clears the terminal. Safe to call multiple times; only initializes once.
Definition at line 155 of file ange.h.
{
    if (ange_initialized) return;
    tcgetattr(STDIN_FILENO, &tui_orig_termios);
    struct termios raw = tui_orig_termios;
    raw.c_lflag &= ~(ECHO | ICANON);
    raw.c_cc[VMIN] = 1;
    raw.c_cc[VTIME] = 0;
    tcsetattr(STDIN_FILENO, TCSANOW, &raw);
    printf("\033[?25l\033[2J\033[H");
    fflush(stdout);
    ange_initialized = 1;
}
References ange_initialized, and tui_orig_termios.
Referenced by angePrintP(), and angePrintP_Unaligned().
angeInputButton()
static int angeInputButton (ange_button_t * buttons, int count) static
Draws a list of buttons and handles user input to select one.
Uses arrow keys to navigate and Enter to select.
Parameters
buttons Array of ange_button_t buttons.
count Number of buttons.
Returns
Index of the selected button.
Definition at line 352 of file ange.h.
{
    int current = 0;
    while (1) {
        angeDrawButton(buttons, count, current);
        ange_input_t input = angeReadKey();
        switch (input.type) {
            case ANGE_KEY_ARROW_UP:
                current = (current - 1 + count) % count;
                break;
            case ANGE_KEY_ARROW_DOWN:
                current = (current + 1) % count;
                break;
            case ANGE_KEY_ENTER:
                return current;
            default:
                break;
        }
    }
}
References ANGE_KEY_ARROW_DOWN, ANGE_KEY_ARROW_UP, ANGE_KEY_ENTER, angeDrawButton(), angeReadKey(), and ange_input_t::type.
angeInputRadio()
static int angeInputRadio (ange_radio_group_t * group) static
Displays a group of radio options and lets the user select one.
Supports navigation with arrow keys, selection with Enter, and cancellation with Escape.
Parameters
group Pointer to an ange_radio_group_t structure.
Returns
Index of the selected radio option, or -1 if cancelled.
Definition at line 383 of file ange.h.
{
    int current = group->selected_index;
    while (1) {
        printf("\033[H");
        for (int i = 0; i < group->count; i++) {
            const char* marker = (i == group->selected_index) ? "(o)" : "( )";
            if (i == current)
                printf("➤ %s %s\n", marker, group->options[i].label);
            else
                printf("  %s %s\n", marker, group->options[i].label);
        }
        fflush(stdout);
        ange_input_t input = angeReadKey();
        switch (input.type) {
            case ANGE_KEY_ARROW_UP:
                current = (current - 1 + group->count) % group->count;
                break;
            case ANGE_KEY_ARROW_DOWN:
                current = (current + 1) % group->count;
                break;
            case ANGE_KEY_ENTER:
                group->selected_index = current;
                return current;
            case ANGE_KEY_ESCAPE:
                return -1;
            default:
                break;
        }
    }
}
References ANGE_KEY_ARROW_DOWN, ANGE_KEY_ARROW_UP, ANGE_KEY_ENTER, ANGE_KEY_ESCAPE, angeReadKey(), ange_radio_group_t::count, ange_radio_option_t::label, ange_radio_group_t::options, ange_radio_group_t::selected_index, and ange_input_t::type.
angeKill()
static void angeKill (void) static
Restores the terminal to its original settings and shows the cursor.
Safe to call multiple times; only deinitializes if previously initialized.
Definition at line 180 of file ange.h.
{
    if (!ange_initialized) return;
    tcsetattr(STDIN_FILENO, TCSANOW, &tui_orig_termios);
    printf("\033[?25h\n");
    fflush(stdout);
    ange_initialized = 0;
}
References ange_initialized, and tui_orig_termios.
angePrintHeader()
static void angePrintHeader (const char * text) static
Prints a header line with larger size.
The header is printed in a larger size.
Parameters
text The null-terminated string to print as header.
Definition at line 311 of file ange.h.
{
    int hasFiglet = system("figlet -v > /dev/null 2>&1");
    char command[512];
    if (hasFiglet == 0) {
        snprintf(command, sizeof(command), "figlet \"%s\"", text);
        system(command);
    } else {
        printf(text); // Fallback to crappy visualizing
    }
    fflush(stdout);
}
angePrintP()
static void angePrintP (const char * text, ange_align_t align) static
Prints a paragraph of text aligned within the terminal width.
Initializes the TUI if not already initialized.
Parameters
text The null-terminated string to print.
align The alignment mode (left, center, right).
Definition at line 255 of file ange.h.
{
    if (!ange_initialized) angeInit();
    int len = strlen(text);
    int pad = 0;
    switch (align) {
        case ANGE_ALIGN_CENTER: pad = (getColSize() - len) / 2; break;
        case ANGE_ALIGN_RIGHT: pad = getColSize() - len; break;
        case ANGE_ALIGN_LEFT: default: pad = 0;
    }
    if (pad < 0) pad = 0;
    printf("\n%*s%s\n", pad, "", text);
    fflush(stdout);
}
References ANGE_ALIGN_CENTER, ANGE_ALIGN_LEFT, ANGE_ALIGN_RIGHT, ange_initialized, angeInit(), and getColSize().
angePrintP_Unaligned()
static void angePrintP_Unaligned (const char * text) static
Prints a paragraph of text without any alignment (left aligned by default).
Initializes the TUI if not already initialized.
Parameters
text The null-terminated string to print.
Definition at line 280 of file ange.h.
{
    if (!ange_initialized) angeInit();
    printf("\033[H%s\n", text);
    fflush(stdout);
}
References ange_initialized, and angeInit().
Referenced by angePrintP_yAlign().
angePrintP_yAlign()
static void angePrintP_yAlign (const char * text, int y_padding_amount) static
Prints a paragraph of text with vertical alignment.
Initializes the TUI if not already initialized (through angePrintP)
Parameters
text The null-terminated string to print.
y_padding_amount The amount of vertical (y-axis) padding to insert
Definition at line 296 of file ange.h.
{
    for (int i = 0; i < y_padding_amount; ++i) {
        printf("\n");
    }
    angePrintP_Unaligned(text);
}
References angePrintP_Unaligned().
angeReadKey()
static ange_input_t angeReadKey (void) static
Reads a key press from standard input and returns it as an ange_input_t structure.
This function supports arrow keys, Enter, Escape, and printable characters.
Returns
ange_input_t representing the pressed key.
Definition at line 77 of file ange.h.
{
    char c;
    ange_input_t input = { ANGE_KEY_UNKNOWN, 0 };
    if (read(STDIN_FILENO, &c, 1) != 1) return input;
    if (c == '\033') {
        char seq[3] = {0};
        fd_set set;
        struct timeval timeout;
        FD_ZERO(&set);
        FD_SET(STDIN_FILENO, &set);
        timeout.tv_sec = 0;
        timeout.tv_usec = 50000;
        int rv = select(STDIN_FILENO + 1, &set, NULL, NULL, &timeout);
        if (rv == 0) {
            input.type = ANGE_KEY_ESCAPE;
            input.ch = 27;
            return input;
        }
        if (read(STDIN_FILENO, &seq[0], 1) != 1) {
            input.type = ANGE_KEY_ESCAPE;
            input.ch = 27;
            return input;
        }
        if (read(STDIN_FILENO, &seq[1], 1) != 1) {
            input.type = ANGE_KEY_ESCAPE;
            input.ch = 27;
            return input;
        }
        if (seq[0] == '[') {
            if (seq[1] >= '0' && seq[1] <= '9') {
                if (read(STDIN_FILENO, &seq[2], 1) != 1) return input;
            } else {
                switch (seq[1]) {
                    case 'A': input.type = ANGE_KEY_ARROW_UP; break;
                    case 'B': input.type = ANGE_KEY_ARROW_DOWN; break;
                    case 'C': input.type = ANGE_KEY_ARROW_RIGHT; break;
                    case 'D': input.type = ANGE_KEY_ARROW_LEFT; break;
                    default: break;
                }
            }
        }
        return input;
    } else if (c == '\177') {
        input.type = ANGE_KEY_BACKSPACE;
        input.ch = 127;
        return input;
    } else if (c == '\n' || c == '\r') {
        input.type = ANGE_KEY_ENTER;
        return input;
    } else if (c >= 32 && c <= 126) {
        input.type = ANGE_KEY_CHAR;
        input.ch = c;
        return input;
    }
    return input;
}
References ANGE_KEY_ARROW_DOWN, ANGE_KEY_ARROW_LEFT, ANGE_KEY_ARROW_RIGHT, ANGE_KEY_ARROW_UP, ANGE_KEY_BACKSPACE, ANGE_KEY_CHAR, ANGE_KEY_ENTER, ANGE_KEY_ESCAPE, ANGE_KEY_UNKNOWN, ange_input_t::ch, and ange_input_t::type.
Referenced by angeDrawNavbar(), angeDrawTextbox(), angeInputButton(), and angeInputRadio().
getColSize()
static int getColSize () static
Returns integer value to terminal coloumn size.
Definition at line 36 of file ange.h.
{
    return atoi(getenv("COLOUMNS"));
}
Referenced by angePrintP().
RestoreCurPos()
static void RestoreCurPos () static
(Development use) Restores the cursor position previously saved.
Definition at line 30 of file ange.h.
{
    printf("\033[u");
}
SaveCurPos()
static void SaveCurPos () static
(Development use) Saves the current cursor position in the terminal.
Definition at line 24 of file ange.h.
{
    printf("\033[s");
}
Variable Documentation
ange_initialized
int ange_initialized = 0 static
Definition at line 42 of file ange.h.
Referenced by angeInit(), angeKill(), angePrintP(), and angePrintP_Unaligned().
tui_orig_termios
struct termios tui_orig_termios static
Definition at line 41 of file ange.h.
Referenced by angeInit(), and angeKill().